### ISSUE TITLE
Need to make cursor pointer when hover

### ISSUE THREAD

**Issue by Saran-pariyar** [faheemk23/Ecommerce-app#41]
The project is great but I think it would be good if you make cursor:pointer to cards and buttons like these places :)

<img width="200" alt="image" src="https://github.com/faheemk23/Ecommerce-app/assets/86418083/b88469d6-2597-453f-98f4-1ea43c6f5191">

<img width="134" alt="image" src="https://github.com/faheemk23/Ecommerce-app/assets/86418083/6aed8709-4d3e-433e-b27c-81f7891f8a96">

<img width="113" alt="image" src="https://github.com/faheemk23/Ecommerce-app/assets/86418083/c71adbe8-d8f7-4f40-838b-45c5b63a81c9">

**Comment by faheemk23** [comment]
@Saran-pariyar Thank you for pointing out this issue. Will surely fix this.
